export const PRIMARY = '#0A42AC'; // Green
export const ACCENT = '#FFB71B'; // Yellow
export const WHITE = '#FFFFFF';
export const BLACK = '#000000';
export const TEXT = '#282828';
export const RED = '#DE4747';
export const BORDER = '#BBBBBB';
export const INACTIVE_TINT_COLOR = '#FFFFFFB3';
export const MILD_GREY = '#F7F7F7';
export const BORDER_GREY = '#C1C1C1';
